version: '3.8'

services:
  bmp-postgres:
    image: postgres:15
    container_name: db-postgres
    env_file:
      - .env
    volumes:
      - bmp-database-record:/var/lib/postgresql/data
    networks:
      - bmp-net
    ports:
      - "5060:5432"
    restart: always
  
  bmp-backend:
    build: ../bmp-be
    container_name: app-be
    env_file:
      - ../bmp-be/.env
    depends_on:
      - bmp-postgres
    ports:
      - "5000:5001"
    networks:
      - bmp-net
    restart: always

  bmp-frontend:
    build: ../bmp-fe
    container_name: app-fe
    env_file:
      - ../bmp-fe/.env
    ports:
      - "3000:3001"
    networks:
      - bmp-net
    restart: always

  bmp-reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - bmp-frontend
      - bmp-backend
    networks:
      - bmp-net
    restart: always

networks:
  bmp-net:

volumes:
  bmp-database-record:
