version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin_bmp_eproc
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: bmp_eproc
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bmpeproc_net
    restart: always

  backend:
    build: ../bmpeproc-be
    # environment:
    #   PORT: 5001
    #   DATABASE_URL: "postgresql://admin_bmp_eproc:admin123@postgres:5432/bmp_eproc?schema=public"
    #   JWT_SECRET: inventory
    env_file:
      - ../bmpeproc-be/.env
    depends_on:
      - postgres
    ports:
      - "5001:5001"
    networks:
      - bmpeproc_net
    restart: always

  frontend:
    build: ../bmpeproc-fe
    # environment:
    #   VITE_API_URL: "/api"
    env_file:
      - ../bmpeproc-fe/.env
    ports:
      - "3000:80"
    networks:
      - bmpeproc_net
    restart: always

  reverse-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - bmpeproc_net
    restart: always

networks:
  bmpeproc_net:

volumes:
  postgres-data:




# version: '3.8'

# services:
#   frontend:
#     build:
#       context: ../bmpeproc-fe-main
#     container_name: app-frontend
#     env_file:
#       - ../bmpeproc-fe-main/.env
#     networks:
#       - bmpeproc_net

#   backend:
#     build:
#       context: ../bmpeproc-be-main
#     container_name: app-backend
#     ports:
#       - "5001:5001"
#     env_file:
#       - ../bmpeproc-be-main/.env
#     networks:
#       - bmpeproc_net
#     depends_on:
#       - postgres

#   postgres:
#     image: postgres:15
#     restart: always
#     environment:
#       POSTGRES_USER: admin_bmp_eproc
#       POSTGRES_PASSWORD: admin123
#       POSTGRES_DB: bmp_eproc
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     networks:
#       - bmpeproc_net

#   nginx:
#     image: nginx:latest
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#     depends_on:
#       - frontend
#       - backend
#     networks:
#       - bmpeproc_net



# networks:
#   bmpeproc_net:

# volumes:
#   postgres_data: